### ISSUE TITLE
i want slide finger from the left to the right,show sidedrawer

### ISSUE THREAD

**Issue by baixiaoyu2997** [rigor789/nativescript-vue-sidedrawer-demo#2]
can u tell me how do it? thanks

**Comment by katk0smos** [comment]
I noticed that you closed this. Did you fix it, or did you figure it out?

**Comment by baixiaoyu2997** [comment]
> 
> 
> I noticed that you closed this. Did you fix it, or did you figure it out?

This component supports this feature by default，maybe my component is installed incorrectly.
